package dev.seabat.android.shinobuetuner.utils.MusicalScale

enum class MusicalScaleType(val ja: String, val en: String) {
    B2("シ", "B2"),
    C3("ド", "C3"),
    Cs3("ド♯", "C#3"),
    D3("レ", "D3"),
    Ds3("レ#", "D#3"),
    E3("ミ", "E3"),
    F3("ファ", "F3"),
    Fs3("ファ#", "F#3"),
    G3("ソ", "G3"),
    Gs3("ソ#", "G#3"),
    A3("ラ", "A3"),
    As3("ラ#", "A#3"),
    B3("シ", "B3"),
    C4("ド", "C4"),
    Cs4("ド♯", "C#4"),
    D4("レ", "D4"),
    Ds4("レ#", "D#4"),
    E4("ミ", "E4"),
    F4("ファ", "F4"),
    Fs4("ファ#", "F#4"),
    G4("ソ", "G4"),
    Gs4("ソ#", "G#4"),
    A4("ラ", "A4"),
    As4("ラ#", "A#4"),
    B4("シ", "B4"),
    C5("ド", "C5"),
    Cs5("ド♯", "C#5"),
    D5("レ", "D5"),
    Ds5("レ#", "D#5"),
    E5("ミ", "E5"),
    F5("ファ", "F5"),
    UNKNOWN("", ""),
}