package dev.seabat.android.shinobuetuner.utils.MusicalScale

enum class MusicalScaleType(val ja: String, val en: String, val level: Int) {
    B2("シ", "B", 2),
    C3("ド", "C", 3),
    Cs3("ド♯", "C#", 3),
    D3("レ", "D", 3),
    Ds3("レ#", "D#", 3),
    E3("ミ", "E", 3),
    F3("ファ", "F", 3),
    Fs3("ファ#", "F#", 3),
    G3("ソ", "G", 3),
    Gs3("ソ#", "G#", 3),
    A3("ラ", "A", 3),
    As3("ラ#", "A#", 3),
    B3("シ", "B3", 3),
    C4("ド", "C", 4),
    Cs4("ド♯", "C#", 4),
    D4("レ", "D", 4),
    Ds4("レ#", "D#", 4),
    E4("ミ", "E", 4),
    F4("ファ", "F", 4),
    Fs4("ファ#", "F#", 4),
    G4("ソ", "G", 4),
    Gs4("ソ#", "G#", 4),
    A4("ラ", "A", 4),
    As4("ラ#", "A#", 4),
    B4("シ", "B", 4),
    C5("ド", "C", 5),
    Cs5("ド♯", "C#", 5),
    D5("レ", "D", 5),
    Ds5("レ#", "D#", 5),
    E5("ミ", "E", 5),
    F5("ファ", "F", 5),
    UNKNOWN("", "", 0),
}